[package]
name = "mango-api"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/ArnoDarkrose/mango-api.git"
licence-file = "LICENSE"
description = "API for the manga reading tool"

[dependencies]
reqwest = "0.12.9"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.41.0", features = ["full"] }
